apiVersion: v1
kind: ConfigMap
metadata:
  name: broadcaster-config
data:
  NATS_URL: "nats://my-nats.nats.svc.cluster.local:4222"
  TODO_EVENTS_SUBJECT: "todo.events"
  BROADCASTER_QUEUE_GROUP: "todo-broadcasters"
  WEBHOOK_MODE: "generic"