apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-log
          emptyDir: {}
      containers:
        - name: log-output-writer
          image: kevinjohn971/log-output-writer:1.10
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files

        - name: log-output-reader
          image: kevinjohn971/log-output-reader:1.10
          env:
            - name: PORT
              value: "3000"
          volumeMounts:
            - name: shared-log
              mountPath: /usr/src/app/files