apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-production

resources:
  - ../../base
  - backup-configmap.yaml
  - backup-cronjob.yaml

patches:
  - path: broadcaster-configmap-patch.yaml

images:
  - name: PROJECT/TODO_APP
    newName: kevinjohn971/todo-app
    newTag: "production"
  - name: PROJECT/TODO_BACKEND
    newName: kevinjohn971/todo-backend
    newTag: "production"
  - name: PROJECT/WIKIPEDIA_TODO_CRON
    newName: kevinjohn971/wikipedia-todo-cron
    newTag: "production"
  - name: PROJECT/BROADCASTER
    newName: kevinjohn971/broadcaster
    newTag: "production"