apiVersion: apps/v1
kind: Deployment
metadata:
  name: broadcaster-dep
  namespace: project
spec:
  replicas: 6
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: kevinjohn971/broadcaster:4.6
          envFrom:
            - configMapRef:
                name: broadcaster-config
          env:
            - name: WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: broadcaster-secret
                  key: WEBHOOK_URL
          resources:
            requests:
              cpu: "20m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"