apiVersion: v1
kind: Secret
metadata:
  name: ping-pong-db-secret
  namespace: exercises
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: pingpongdb
  DATABASE_URL: postgresql://postgres:postgres@ping-pong-postgres-svc:5432/pingpongdb