apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-app-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-app
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      volumes:
        - name: project-data
          persistentVolumeClaim:
            claimName: project-claim
      containers:
        - name: todo-app
          image: kevinjohn971/todo-app:2.6
          envFrom:
            - configMapRef:
                name: todo-app-config
          volumeMounts:
            - name: project-data
              mountPath: /usr/src/app/files