apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project

resources:
  - todo-app-configmap.yaml
  - todo-app-pvc.yaml
  - todo-app-deployment.yaml
  - todo-app-service.yaml
  - todo-backend-configmap.yaml
  - todo-backend-deployment.yaml
  - todo-backend-service.yaml
  - todo-postgres-secret.yaml
  - todo-postgres-statefulset.yaml
  - wikipedia-cronjob.yaml
  - ../broadcaster/manifests/configmap.yaml
  - ../broadcaster/manifests/deployment.yaml

images:
  - name: PROJECT/TODO_APP
    newName: kevinjohn971/todo-app
    newTag: "4.5"
  - name: PROJECT/TODO_BACKEND
    newName: kevinjohn971/todo-backend
    newTag: "4.6"
  - name: PROJECT/WIKIPEDIA_TODO_CRON
    newName: kevinjohn971/wikipedia-todo-cron
    newTag: "3.5"
  - name: PROJECT/BROADCASTER
    newName: kevinjohn971/broadcaster
    newTag: "4.6"