apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: todo-backend
          image: kevinjohn971/todo-backend:2.8
          envFrom:
            - configMapRef:
                name: todo-backend-config
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: todo-db-secret
                  key: DATABASE_URL